"""
tests/smoke_tests.py — smoke tests for all 15 pathfinding algorithms.

Uses an 11×21 simply-connected maze generated by iterative DFS with seed 42.
The maze is a perfect spanning tree over logical cells, meaning there is
exactly one path between any two logical cells — the canonical form for
testing pathfinding algorithms.

ALGORITHM CATEGORIES
--------------------
OPTIMAL        — guaranteed to find the shortest path.  Tested: path_len
               equals BFS optimal.  (BFS, A*, Dijkstra, IDA*, Bellman-Ford)

NONCOMPLETE    — correct but not guaranteed to succeed on every maze topology.
               Tested: terminates within step cap. Path quality is not
               asserted.  (Wall Follower, Left-Hand Rule, Pledge, Random Mouse,
               Randomized DFS)  Wall followers fail on mazes with isolated
               wall islands — which this maze has by construction — and that
               is the documented, expected behaviour.

All others     — find some path but not necessarily the shortest.  Tested:
               path_len > 0 and path_cost >= path_len - 1.

Usage (from project root):
    python tests/smoke_tests.py
    python tests/smoke_tests.py -v
    python tests/smoke_tests.py --fast

Exit code 0 = all pass, 1 = any failure.
"""

from __future__ import annotations

import collections
import random
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from algorithms.registry import _REGISTRY, _get_generator
from core.graph import validate_path, validate_yield

# ---------------------------------------------------------------------------
# Maze generator — embedded, self-contained
# ---------------------------------------------------------------------------

def _generate_dfs_maze(
    log_rows: int,
    log_cols: int,
    seed:     int,
) -> list[list[int | str]]:
    """Generate a perfect maze via iterative DFS, S at (0,0), E at (rows-1,cols-1).

    Grid size: (2*log_rows - 1) × (2*log_cols - 1).  Logical cells occupy
    even-indexed positions.  Walls between cells occupy odd-indexed positions.
    S is placed at (0,0) and E at (rows-1,cols-1) so all 15 algorithms work
    without modification — every algorithm starts at (0,0) and targets
    (rows-1,cols-1).

    Post walls at (odd_row,odd_col) are interior-only and not connected to
    the outer boundary; this is the documented reason wall-following algorithms
    are classified NONCOMPLETE on DFS-generated mazes.
    """
    rng   = random.Random(seed)
    rows  = 2 * log_rows - 1
    cols  = 2 * log_cols - 1
    maze  = [[1] * cols for _ in range(rows)]

    # Carve starting cell at (0,0)
    maze[0][0] = 0

    stack   = [(0, 0)]
    visited = {(0, 0)}

    while stack:
        r, c  = stack[-1]
        dirs  = [(-2, 0), (0, 2), (2, 0), (0, -2)]
        rng.shuffle(dirs)

        moved = False
        for dr, dc in dirs:
            nr, nc = r + dr, c + dc
            if (0 <= nr < rows and 0 <= nc < cols and (nr, nc) not in visited):
                maze[(r + nr) // 2][(c + nc) // 2] = 0   # carve dividing wall
                maze[nr][nc] = 0
                visited.add((nr, nc))
                stack.append((nr, nc))
                moved = True
                break

        if not moved:
            stack.pop()

    # S and E at grid corners — exactly where algorithms expect them
    maze[0][0]               = 'S'
    maze[rows - 1][cols - 1] = 'E'
    return maze


# ---------------------------------------------------------------------------
# Test maze  —  6 × 11 logical  →  11 × 21 grid, seed 42
# ---------------------------------------------------------------------------
# Grid size: (2*6-1) × (2*11-1) = 11×21 = 231 cells.
# S at (0,0), E at (10,20) = (rows-1, cols-1) — matches algorithm expectations.
# BFS optimal path (computed in run_all): ~41 intermediate cells.
# Dead ends: sufficient for Dead-End Filling.
# IDA* and Bellman-Ford complete comfortably in under a second at this size.
#
MAZE_LOG_ROWS, MAZE_LOG_COLS, MAZE_SEED = 6, 11, 42
SMOKE_MAZE: list[list[int | str]] = _generate_dfs_maze(
    MAZE_LOG_ROWS, MAZE_LOG_COLS, MAZE_SEED
)

# ---------------------------------------------------------------------------
# Algorithm classifications
# ---------------------------------------------------------------------------

# These five always return the optimal (shortest / cheapest) path.
OPTIMAL_ALGOS = {"bfs", "astar", "dijkstra", "ida_star", "bellman_ford"}

# Non-complete: may or may not reach E.  Only termination is tested.
# Includes wall followers (fail on non-simply-connected mazes by design)
# and stochastic algorithms that may hit the step cap.
NONCOMPLETE_ALGOS = {
    "wall_follower", "left_hand", "pledge",
    "random_mouse",  "randomized_dfs",
    "beam_search",   "flood_fill",
}

# Algorithms that produce valid any-angle paths where intermediate cells are
# intentionally skipped via line-of-sight shortcuts.  The standard adjacency
# check in validate_path (which expects every P cell to be a grid-neighbour
# of the next) does not apply to these algorithms.
SKIP_PATH_VALIDATE = {"theta_star"}

# These take significantly longer on large mazes.
SLOW_ALGOS = {"bellman_ford", "ida_star", "random_mouse"}

# Filled by run_all() once _bfs_optimal is available.
OPTIMAL_PATH_LEN: int = 0


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _bfs_optimal(maze: list[list[int | str]]) -> int:
    """Shortest path from S to E in *maze*.

    Locates S and E by scanning the grid so the function works regardless
    of whether the maze has an outer wall border. Returns the cell count
    including S and E, or 0 when no path exists.
    """
    rows, cols = len(maze), len(maze[0])
    passable   = {0, 'S', 'E', '~'}
    dirs       = [(-1, 0), (0, 1), (1, 0), (0, -1)]

    start = goal = None
    for r in range(rows):
        for c in range(cols):
            if maze[r][c] == 'S':
                start = (r, c)
            elif maze[r][c] == 'E':
                goal = (r, c)

    if start is None or goal is None:
        return 0

    q       = collections.deque([(start[0], start[1], 1)])
    visited = {start}

    while q:
        r, c, d = q.popleft()
        if (r, c) == goal:
            return d
        for dr, dc in dirs:
            nr, nc = r + dr, c + dc
            if (0 <= nr < rows and 0 <= nc < cols
                    and (nr, nc) not in visited
                    and maze[nr][nc] in passable):
                visited.add((nr, nc))
                q.append((nr, nc, d + 1))
    return 0


def _fresh_maze() -> list[list[int | str]]:
    return [row[:] for row in SMOKE_MAZE]


def _run_algo(
    solve_fn,
    maze_copy: list,
    step_cap:  int  = 150_000,
    algo_name: str  = "",
):
    """Consume *solve_fn* to completion, return its RunResult.

    Raises RuntimeError if *step_cap* steps pass without a 'done' event —
    this catches infinite loops and prevents CI from hanging.
    """
    gen   = solve_fn(maze_copy)
    steps = 0
    for state in gen:
        # Every yielded dict must conform to the generator contract.
        # This catches missing keys and wrong types in new algorithm
        # implementations before they can crash the animation loop.
        contract_err = validate_yield(state, algo_name=algo_name)
        if contract_err:
            raise RuntimeError(f"Contract violation: {contract_err}")

        if state.get("type") == "done":
            return state.get("result")
        steps += 1
        if steps > step_cap:
            raise RuntimeError(
                f"Did not terminate after {step_cap:,} steps "
                f"(last type={state.get('type')!r})"
            )
    raise RuntimeError("Generator exhausted without a 'done' event.")


# ---------------------------------------------------------------------------
# Test runner
# ---------------------------------------------------------------------------

def run_all(verbose: bool = False, skip_slow: bool = False) -> bool:
    """Run all registered algorithms and report results.

    Returns True when every test passes, False otherwise.
    """
    global OPTIMAL_PATH_LEN

    bfs_cells        = _bfs_optimal(SMOKE_MAZE)
    OPTIMAL_PATH_LEN = max(0, bfs_cells - 2)   # excludes S and E cells

    if bfs_cells == 0:
        print("FATAL: SMOKE_MAZE has no solution — check maze generation.")
        return False

    rows, cols = len(SMOKE_MAZE), len(SMOKE_MAZE[0])
    passable   = {0, 'S', 'E', '~'}
    dirs       = [(-1, 0), (0, 1), (1, 0), (0, -1)]

    dead_ends = sum(
        1 for r in range(rows) for c in range(cols)
        if SMOKE_MAZE[r][c] in passable
        and (r, c) not in ((0, 0), (rows - 1, cols - 1))
        and sum(1 for dr, dc in dirs
                if 0 <= r+dr < rows and 0 <= c+dc < cols
                and SMOKE_MAZE[r+dr][c+dc] in passable) == 1
    )

    if verbose:
        print(f"  Maze: {rows}×{cols}  seed={MAZE_SEED}  "
              f"BFS={bfs_cells} cells  "
              f"OPTIMAL_PATH_LEN={OPTIMAL_PATH_LEN}  "
              f"dead_ends={dead_ends}")
        print(f"  Wall-following algorithms are NONCOMPLETE on this maze")
        print(f"  (simply-connected guarantee requires no interior wall islands)")
        print()

    passed = []
    failed = []

    for spec in _REGISTRY:
        name = spec.display_name
        mod  = spec.module_name

        if skip_slow and mod in SLOW_ALGOS:
            print(f"  SKIP  {name} (--fast)")
            continue

        errors: list[str] = []

        try:
            random.seed(MAZE_SEED)
            maze_copy = _fresh_maze()
            solve_fn  = _get_generator(mod)
            cap       = 1_000_000 if mod == "random_mouse" else 150_000
            result    = _run_algo(solve_fn, maze_copy, cap, algo_name=name)

        except Exception as exc:
            failed.append((name, [f"Exception: {type(exc).__name__}: {exc}"]))
            print(f"  FAIL  {name}")
            if verbose:
                import traceback
                traceback.print_exc()
            continue

        if result is None:
            errors.append("'done' event had no result object")

        elif mod in NONCOMPLETE_ALGOS:
            # Only check: terminates cleanly and step count is sane.
            if result.steps < 0:
                errors.append(f"steps={result.steps} (expected ≥ 0)")
            # If it found a path, sanity-check cost
            if result.path_len > 0 and result.path_cost < result.path_len - 1:
                errors.append(
                    f"path_cost {result.path_cost} < path_len-1 {result.path_len - 1}"
                )

        else:
            # Must find a path
            if result.path_len <= 0:
                errors.append(f"path_len={result.path_len} — no path found")

            elif result.path_cost < result.path_len - 1:
                errors.append(
                    f"path_cost {result.path_cost} < path_len-1 {result.path_len - 1} "
                    f"(terrain cost cannot be less than hop count)"
                )

            elif mod in OPTIMAL_ALGOS and result.path_len != OPTIMAL_PATH_LEN:
                errors.append(
                    f"path_len {result.path_len} ≠ expected {OPTIMAL_PATH_LEN} "
                    f"({name} claims optimal)"
                )

            elif bfs_cells == 0 and result.path_len > 0:
                errors.append("found a path on an unsolvable maze (phantom path)")

            else:
                # Physical path check — P cells must form a connected route S→E
                # Skipped for any-angle algorithms (e.g. Theta*) that intentionally
                # jump over intermediate cells via line-of-sight shortcuts.
                if mod not in SKIP_PATH_VALIDATE:
                    path_err = validate_path(maze_copy, result.path_len, result.path_cost)
                    if path_err:
                        errors.append(f"path correctness: {path_err}")

            if result.steps == float("inf") and result.path_len > 0:
                errors.append("steps=inf but path_len>0 — inconsistent result")

        if errors:
            failed.append((name, errors))
            print(f"  FAIL  {name}")
            if verbose:
                for e in errors:
                    print(f"         • {e}")
        else:
            passed.append(name)
            if verbose:
                r   = result
                cat = ("noncomplete" if mod in NONCOMPLETE_ALGOS
                       else "optimal" if mod in OPTIMAL_ALGOS
                       else "finds path")
                found = f"path_len={r.path_len}" if r.path_len > 0 else "no path (ok)"
                print(
                    f"  pass  {name:<28} "
                    f"steps={int(r.steps):>8}  "
                    f"{found:<14}  "
                    f"cost={r.path_cost:<4}  [{cat}]"
                )
            else:
                print(f"  pass  {name}")

    print()
    print(f"  {len(passed)} passed  |  {len(failed)} failed")

    if failed:
        print()
        for name, errs in failed:
            print(f"  FAIL: {name}")
            for e in errs:
                print(f"    • {e}")

    return len(failed) == 0


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    args    = sys.argv[1:]
    verbose = "-v" in args or "--verbose" in args
    fast    = "--fast" in args

    bfs_all = _bfs_optimal(SMOKE_MAZE)
    rows    = len(SMOKE_MAZE)
    cols    = len(SMOKE_MAZE[0])

    print()
    print(f"  Algorithm Encyclopedia — Smoke Tests")
    print(f"  Maze: {rows}×{cols}  seed={MAZE_SEED}  "
          f"BFS={bfs_all} cells  "
          f"OPTIMAL_PATH_LEN={max(0, bfs_all-2)}")
    print(f"  {'─' * 60}")

    ok = run_all(verbose=verbose, skip_slow=fast)
    print()
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()